### PR TITLE
Sanitize arrays

### PR DESCRIPTION
**Pull request by szepeviktor**
@filisko And exclude additional IDE files.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@filisko Is it OK to merge?

**Comment by szepeviktor** [comment]
@filisko Could you take a look at it?

**Comment by szepeviktor** [comment]
@filisko Could you take a look at it?

**Comment by filisko** [comment]
@szepeviktor why use filter_basic_tags to sanitize?

**Comment by szepeviktor** [comment]
I think for filtering out HTML tags.
@cay89 Could you advise?

**Comment by cay89** [comment]
> I think for filtering out HTML tags.
> @cay89 Could you advise?

It works fine in our project, but I'm not sure it's a general solution.

**Comment by filisko** [comment]
6a71281

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
