### PR TITLE
Adding Indonesian Language

### PR DESCRIPTION
**Pull request by rikylesmana**
@filisko done removing the array_column support.
how can i add this without the array_column function in php 5.4 ?

### CODE REVIEW

**Comment by zhanza** [comment]
Hello @filisko, seem cannot passed the check because the php 5.4 array_column issue

**Comment by filisko** [comment]
Yes, I've just removed 5.4 version. I will merge it now anyway :)

**Comment by filisko** [comment]
You removed the array_column support but forget to leave the lang file. I just added it

**Comment by rikylesmana** [comment]
Thanks any way, i just need the language to be add.
Thanks  @filisko

**Comment by filisko** [comment]
@rikylesmana, thank you!

**Pull request merged**
