### PR TITLE
Fatal error on sanitize call on line 309

### PR DESCRIPTION
**Pull request by NickMitin**
Fixes fatal error: Call to undefined function sanitize() in /home/pharmakey.ru/projects/bric/vendor/wixel/gump/gump.class.php on line 309.

### CODE REVIEW

**Comment by NickMitin** [comment]
Why checks failed? On my website everything is working fine.

**Comment by hammermaps** [comment]
+1

**Comment by swissspidy** [comment]
> Why checks failed? On my website everything is working fine.

Because the function `sanitize()` doesn't exist in PHP.

**Comment by filisko** [comment]
This was already fixed.

Cheers

**Pull request closed without merging**
