### PR TITLE
Phone Number validator & Custom Regex

### PR DESCRIPTION
**Pull request by pl4g4**
I added 2 new validators to match phone numbers, and to have a custom regex validator for those who need it. I had to change a bit the code because of the explode ',' . For now it will explode &&& if its the regex rule. I made an if statement to have , working for the other validators.

### CODE REVIEW

**Comment by NekoKetsu** [comment]
The regexp for phone will depend of the country, you should rename it to validate_phone_number_eng or validate_phone_number_us (i don't know wich one it is).

assuming tha x is a digit
In france we have 0x xx xx xx xx or +33x xx xx xx xx (for international to france)
(Sorry for my bad english by the way)

**Comment by pl4g4** [comment]
Yes, This phone number val will work for US and Canada for sure. I'm from el salvador and we have xxx-xxxx-xxxx . which will fail. I will rename the function to validate_phone_number_us. If you need to validate a new phone format you could always use the regex function i've added.

**Comment by pl4g4** [comment]
I have added a json string validator just to make sure if the string {} you are getting will be a valid object after you convert it using json decode.

**Comment by SeanNieuwoudt** [comment]
Thanks for this one Ron, I've merged it into master.

**Pull request closed without merging**
