### PR TITLE
fixed pipe/comma problem for regex - added example array validation

### LINKED ISSUE #49: regex validator
Hi,

Is it a good idea to introduce a regex validator?

### PR DESCRIPTION
**Pull request by pl4g4**
fixes issue #102...

close #49

### CODE REVIEW

**Comment by pl4g4** [comment]
What were the conflicts ? my change fixes a bug with the regex validation.

**Comment by filisko** [comment]
@pl4g4, first of all thank you.

But your approach does not solve the pipeline ( | ) problem, I mean, it may work for regex validation but we will still with the same problem, a lot of our validation methods can have a pipeline as a parameter (e.g.: contains).

**Comment by Floofies** [comment]
His changes do fix the problem, and not just for regex rules; however the catch is you must properly escape such characters in other rules if you want them to be interpreted literally. Interpreting characters literally by default, with no escaping, _is bad practice in the first place_; and is what caused this problem to begin with. Escaping is a standard practice in string based parsing such as this and should not be too much of a pain to require when you want to target that character in a rule. The same goes for commas.

Here's an example of the type of rule made possible by the fix:
```PHP
"ccExpiryInput" => "required|max_len,7|regex,/\d{2}( \/ |\/)\d{2,4}/"
```
Here's another example showing the required escaping in other rules targeting pipe characters:
```PHP
"pipesInput" => "contains,\|"
```

**Comment by filisko** [comment]
@Floofies, did you test this?

```php
"pipesInput" => "contains,\|"
```

**Comment by pl4g4** [comment]
Yes thsi might just 'fix' the regex. I could do more testing. Escaping regex could be hard do. it will need a lot of testing.

**Comment by Floofies** [comment]
@filisko No, it is not implemented. I was outlining the additional change in syntax required to fix this issue completely. As long as regular expressions are supported in the rule syntax, escaping must be supported in all rules and rule types.

**Comment by filisko** [comment]
@Floofies, feel free to do a PR. Thank you.

**Comment by filisko** [comment]
https://github.com/Wixel/GUMP/releases/tag/v1.7.0

**Pull request closed without merging**
