### PR TITLE
Add validate functions to check if is an array and to check array size

### PR DESCRIPTION
**Pull request by GuillaumeSmaha**

### CODE REVIEW

**Comment by majoess** [comment]
I think GUMP is dead.

**Comment by GuillaumeSmaha** [comment]
@majoess Yes I think too

**Comment by filisko** [comment]
@GuillaumeSmaha @majoess, not dead but it was inactive for a while.

Question: Do we really need something like that in GUMP? I mean, how it could be used on a web form for example?

**Comment by GuillaumeSmaha** [comment]
@filisko It can be usefull  when you have a list of checkbox and you need, for example, two checkboxes checked at least

	<input name="type[]" value="1">
	<input name="type[]" value="2">
	<input name="type[]" value="3">
	<input name="type[]" value="4">

**Comment by filisko** [comment]
Thank you @GuillaumeSmaha ! Just adapted your code (ie. lang file)

**Comment by GuillaumeSmaha** [comment]
@filisko You're welcome. Thank's for the merge :)

**Comment by jmbelloteau** [comment]
happy to see Gump is back from the dead ^^

**Pull request closed without merging**
